export const GET_CAROUSEL_IMAGES = 'GET_CAROUSEL_IMAGES';

export const LoginTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    CLEAR_ERROR: 'CLEAR_ERROR'
}

export const UserTypes = {
    SET_USER_INFO: 'SET_USER_INFO'
}